common:
  lidar_topic:  "/livox/lidar_192_168_30_201"
  lidar_topic2: "/livox/lidar_192_168_30_202"
  imu_topic:  "/livox/imu_192_168_30_202"
  imu_init_count: 400

preprocess:
  lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
  scan_line: 4
  blind: 0.3

mapping:
  acc_cov: 0.01
  gyr_cov: 0.00004
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001
  fov_degree: 360
  det_range:  50.0
  extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
  extrinsic_T: [-0.011, -0.02329, 0.04412]  # Lidar在IMU坐标系中的位置
  extrinsic_R: [1, 0, 0,  # 从LiDAR坐标系旋转到IMU坐标系的旋转矩阵
                0, 1, 0,
                0, 0, 1]
  lidar2base_T: [-0.245, 0.000, 0.153] # 后置Lidar在载体中心坐标系中的位置
  lidar2base_R: [-0.8660254,  0.0,  -0.5,  # 从后置LiDAR坐标系旋转到载体中心坐标系的旋转矩阵
                  0.0,       -1.0,   0.0,
                 -0.5,        0.0,   0.8660254]
  # lidar2base_R: [0.8660254,  0.0,  0.5,  # 从前置LiDAR坐标系旋转到载体中心坐标系的旋转矩阵
  #                0.0,        1.0,  0.0,
  #               -0.5,        0.0,  0.8660254]


publish:
  path_en:  true
  scan_publish_en:  true       # false: close all the point cloud output
  dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
  pcd_save_en: true
  interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
